(ns xyz.psyclyx.light.mosquitto
  "Supervised mosquitto broker.

   psyclight owns its own mosquitto: anonymous, loopback only, no
   persistence. The config file is generated under the runtime dir on
   each start. There is no stable system-wide config to clash with."
  (:require [clojure.java.io :as io]
            [clojure.tools.logging :as log]
            [com.stuartsierra.component :as component]
            [xyz.psyclyx.light.process :as process]))

;; -- Config rendering -----------------------------------------------------

(defn- render-conf
  [{:keys [host port]}]
  (str "# Generated by psyclight; do not edit.\n"
       "listener " port " " host "\n"
       "allow_anonymous true\n"
       "persistence false\n"
       "log_dest stdout\n"
       "log_type error\n"
       "log_type warning\n"
       "log_type notice\n"))

(defn- write-conf! [{:keys [config]}]
  (let [{:keys [conf-path]} (:mosquitto config)
        contents             (render-conf (:mqtt config))]
    (some-> (.getParent (io/file conf-path)) io/file .mkdirs)
    (spit conf-path contents)
    conf-path))

;; -- Component ------------------------------------------------------------

(defrecord Mosquitto [config handle]
  component/Lifecycle
  (start [this]
    (let [conf-path (write-conf! this)
          bin       (get-in config [:mosquitto :bin])
          handle    (process/spawn! {:name    "mosquitto"
                                     :command [bin "-c" conf-path]})]
      (log/info "mosquitto started" {:conf conf-path})
      (assoc this :handle handle)))
  (stop [this]
    (when handle (process/stop! handle))
    (assoc this :handle nil)))

(defn mosquitto [] (map->Mosquitto {}))
